spring:
  application:
    name: event-sourcing-app

  mvc:
    problemdetails:
      enabled=true:

  datasource:
    url: jdbc:postgresql://localhost:5432/loyaltysystem
    username: myuser
    password: secret

