

CREATE TABLE IF NOT EXISTS PRODUCT_EVENT_TYPES(
    ID              SERIAL PRIMARY KEY,
    NAME            TEXT NOT NULL,
    DESCRIPTION     TEXT,
    SCHEMA          JSONB NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUCT_EVENTS (
    ID              SERIAL PRIMARY KEY,
    TYPE            INTEGER NOT NULL REFERENCES PRODUCT_EVENT_TYPES(ID)
);