
CREATE TABLE IF NOT EXISTS RESTRICTION (
    ID              SERIAL      PRIMARY KEY,
    TITLE           TEXT        NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUCT_RESTRICTION (
    ID              SERIAL      PRIMARY KEY,
    PRODUCT_ID      UUID     REFERENCES PRODUCT(ID),
    RESTRICTION_ID  INTEGER     REFERENCES RESTRICTION(ID),
    VALID_FROM      TIMESTAMPTZ NOT NULL,
    VALID_TO        TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS CATEGORY (
    ID              SERIAL      PRIMARY KEY,
    NAME            TEXT        NOT NULL
);

CREATE TABLE IF NOT EXISTS ATTRIBUTE (
    ID              SERIAL      PRIMARY KEY,
    NAME            TEXT        NOT NULL
);

CREATE TABLE IF NOT EXISTS CATEGORY_ATTRIBUTES (
    CATEGORY_ID     INTEGER     REFERENCES CATEGORY(ID),
    ATTRIBUTE_ID    INTEGER     REFERENCES ATTRIBUTE(ID),
    PRIMARY KEY(CATEGORY_ID, ATTRIBUTE_ID)
);

CREATE TABLE IF NOT EXISTS PRODUCT_SPECIFICATION (
    ID              SERIAL      PRIMARY KEY,
    ATTRIBUTE_ID    INTEGER     REFERENCES ATTRIBUTE(ID),
    PRODUCT_ID      UUID        REFERENCES PRODUCT(ID),
    SPEC_VALUE      TEXT        NOT NULL
);